//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
// TEXCOORD                 1   xyzw        3     NONE   float   xyz 
// TEXCOORD                 2   xyzw        4     NONE   float       
// TEXCOORD                 3   xyz         5     NONE   float       
// TEXCOORD                 5   xyzw        6     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_4_0
      0x00000008: dcl_constantbuffer CB0[23], immediateIndexed
      0x00000018: dcl_constantbuffer CB1[1], immediateIndexed
      0x00000028: dcl_sampler s0, mode_default
      0x00000034: dcl_sampler s1, mode_default
      0x00000040: dcl_sampler s2, mode_default
      0x0000004C: dcl_resource_texture2d (float,float,float,float) t0
      0x0000005C: dcl_resource_texture2d (float,float,float,float) t1
      0x0000006C: dcl_resource_texture2d (float,float,float,float) t2
      0x0000007C: dcl_input_ps linear v1.xyzw
      0x00000088: dcl_input_ps linear v2.xy
      0x00000094: dcl_input_ps linear v3.xyz
      0x000000A0: dcl_input_ps linear v6.xyzw
      0x000000AC: dcl_output o0.xyzw
      0x000000B8: dcl_temps 4
   0  0x000000C0: sample r0.xyzw, v2.xyxx, t0.xyzw, s2
   1  0x000000E4: add r0.x, r0.w, -v3.x
   2  0x00000104: add r0.y, -r0.w, v3.z
   3  0x00000124: lt r0.x, r0.x, l(0.000000)
   4  0x00000140: discard_nz r0.x
   5  0x0000014C: mul r0.x, cb0[6].x, cb0[22].w
   6  0x00000170: mul r0.x, r0.x, v3.y
   7  0x0000018C: min r0.z, r0.x, l(1.000000)
   8  0x000001A8: mul r0.x, r0.x, l(0.500000)
   9  0x000001C4: sqrt r0.z, r0.z
  10  0x000001D8: mad_sat r0.w, r0.y, v3.y, r0.x
  11  0x000001FC: mad r0.x, r0.y, v3.y, -r0.x
  12  0x00000224: mul r0.y, r0.z, r0.w
  13  0x00000240: mad r0.zw, cb0[4].zzzw, cb1[0].yyyy, v6.zzzw
  14  0x0000026C: sample r1.xyzw, r0.zwzz, t2.xyzw, s1
  15  0x00000290: mul r1.xyzw, r1.xyzw, cb0[5].xyzw
  16  0x000002B0: mul r1.xyz, r1.wwww, r1.xyzx
  17  0x000002CC: mul r2.xyz, v1.xyzx, cb0[3].xyzx
  18  0x000002EC: mad r0.zw, cb0[2].xxxy, cb1[0].yyyy, v6.xxxy
  19  0x00000318: sample r3.xyzw, r0.zwzz, t1.xyzw, s0
  20  0x0000033C: mul r2.xyz, r2.xyzx, r3.xyzx
  21  0x00000358: mul r3.w, r3.w, cb0[3].w
  22  0x00000378: mul r3.xyz, r2.xyzx, r3.wwww
  23  0x00000394: add r1.xyzw, r1.xyzw, -r3.xyzw
  24  0x000003B4: mad r1.xyzw, r0.yyyy, r1.xyzw, r3.xyzw
  25  0x000003D8: mul r0.y, cb0[4].y, cb0[22].w
  26  0x000003FC: mul r0.z, r0.y, v3.y
  27  0x00000418: mad r0.y, r0.y, v3.y, l(1.000000)
  28  0x0000043C: mad r0.x, r0.z, l(0.500000), r0.x
  29  0x00000460: div_sat r0.x, r0.x, r0.y
  30  0x0000047C: add r0.x, -r0.x, l(1.000000)
  31  0x0000049C: mul r0.xyzw, r0.xxxx, r1.xyzw
  32  0x000004B8: mul o0.xyzw, r0.xyzw, v1.wwww
  33  0x000004D4: ret 
// Approximately 0 instruction slots used
